name: stroll-squard CI

on:
  pull_request:
    branches:
      - "develop"
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Environment variables
        run: |
          echo "${{ secrets.DOT_ENV }}" > ./.env
          echo "${{ secrets.TEST_DOT_ENV }}" > ./test.env

      - name: gradlew build
        run: ./gradlew build
